export const types = {
  LOGIN_USER: 'LOGIN_USER',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  UPDATE_SIGN_IN: 'UPDATE_SIGN_IN',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  RESET_PASSWORD: 'RESET_PASSWORD',
  REGISTER_USER: 'REGISTER_USER',
  SET_TAB_COLOR: 'SET_TAB_COLOR',
  GET_COUNTRY_LIST: 'GET_COUNTRY_LIST',
  VERIFY_OTP: 'VERIFY_OTP',
  SET_NEW_PASSWORD: 'SET_NEW_PASSWORD',
  ACTIVE_SUB_MODULE: 'ACTIVE_SUB_MODULE',

  //Pet Types
  GET_PET_LIST: 'GET_PET_LIST',
  DELETE_PET: 'DELETE_PET',
  GET_PET_VACCINE_MENU_LIST: 'GET_PET_VACCINE_MENU_LIST',
  GET_PET_VACCINATION_LIST: 'GET_PET_VACCINATION_LIST',
  ADD_PET_VACCINE: 'ADD_PET_VACCINE',
  GET_PET_ART_LIST: 'GET_PET_ART_LIST',
  GET_PET_RACE_LIST: 'GET_PET_RACE_LIST',
  CREATE_PET: 'CREATE_PET',
  UPLOAD_PET_PROFILE_IMAGE: 'UPLOAD_PET_PROFILE_IMAGE',
  GET_PET_DETAILS: 'GET_PET_DETAILS',
  UPDATE_PET_DETAILS: 'UPDATE_PET_DETAILS',
  UPDATE_NEW_FORM_ID: 'UPDATE_NEW_FORM_ID',
  PET_IDENTIFICATION_OF_ANIMAL: 'PET_IDENTIFICATION_OF_ANIMAL',
  GET_IDENTIFICATION_OF_ANIMAL: 'GET_IDENTIFICATION_OF_ANIMAL',
  PET_ISSUE_OF_IDENTITY_CARD: 'PET_ISSUE_OF_IDENTITY_CARD',
  GET_ISSUE_OF_IDENTITY_CARD: 'GET_ISSUE_OF_IDENTITY_CARD',
  UPDATE_VACCINATION_OBJECT: 'UPDATE_VACCINATION_OBJECT',
  UPDATE_PET_OBJECT: 'UPDATE_PET_OBJECT',
  
  //Member Types
  GET_COMMUNITY_MEMBER_LIST: 'GET_COMMUNITY_MEMBER_LIST',
  GET_SEARCH_USER_LIST: 'GET_SEARCH_USER_LIST',
  GET_SEARCH_PET_LIST: 'GET_SEARCH_PET_LIST',

  // HOME ACTION
  GET_MISSING_PET_LIST: 'GET_MISSING_PET_LIST',
  GET_MY_PET_LIST: 'GET_MY_PET_LIST',
  UPDATE_MISSING_PET: 'UPDATE_MISSING_PET',
  UPDATE_MISSING_SUCCESS: 'UPDATE_MISSING_SUCCESS',
  UPDATE_CURRENT_LOCATION: 'UPDATE_CURRENT_LOCATION',

  // PROFILE ACTIONS
  GET_USER_PROFILE: 'GET_USER_PROFILE',
  UPDATE_USER_PROFILE_PIC: 'UPDATE_USER_PROFILE_PIC',
  GET_BANNER_IMAGE: 'GET_BANNER_IMAGE',
  UPDATE_BANNER_IMAGE: 'UPDATE_BANNER_IMAGE',
  GET_PROFILE_FIELDS: 'GET_PROFILE_FIELDS',
  UPDATE_PROFILE: 'UPDATE_PROFILE',

  //Notification
  GET_NOTIFICATION_LIST: 'GET_NOTIFICATION_LIST'
};
