export const types = {
  LOGIN_USER: 'LOGIN_USER',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  UPDATE_SIGN_IN: 'UPDATE_SIGN_IN',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  RESET_PASSWORD: 'RESET_PASSWORD',
  REGISTER_USER: 'REGISTER_USER',
  SET_TAB_COLOR: 'SET_TAB_COLOR',

  //Pet Types
  GET_PET_LIST: 'GET_PET_LIST',
  DELETE_PET: 'DELETE_PET',
  GET_PET_VACCINE_MENU_LIST: 'GET_PET_VACCINE_MENU_LIST',
  GET_PET_VACCINATION_LIST: 'GET_PET_VACCINATION_LIST',
  ADD_PET_VACCINE: 'ADD_PET_VACCINE',
  
  // HOME ACTION
  GET_MISSING_PET_LIST: 'GET_MISSING_PET_LIST',
  GET_MY_PET_LIST: 'GET_MY_PET_LIST',
  UPDATE_MISSING_PET: 'UPDATE_MISSING_PET',

  // PROFILE ACTIONS
  GET_USER_PROFILE: 'GET_USER_PROFILE',
  UPDATE_USER_PROFILE_PIC: 'UPDATE_USER_PROFILE_PIC',
  GET_BANNER_IMAGE: 'GET_BANNER_IMAGE',
  UPDATE_BANNER_IMAGE: 'UPDATE_BANNER_IMAGE',
};
